### ISSUE TITLE
Update list with new service

### ISSUE THREAD

**Issue by ar-anvd** [tompec/wp.validator.pizza#1]
Hello. I would like to help submitting disposable services to keep validator.pizza great. For example

https://www.minuteinbox.com

@tompec

**Comment by tompec** [comment]
Hey, thanks for your help @ar-anvd! I use [this repository](https://github.com/ivolo/disposable-email-domains) as one of my source for validator.pizza, so feel free to submit a PR there and it'll be added automatically.
I've just added `0ioi.net` from minuteinbox.com
Cheers!
